const MODULE_ID = "maurei-isle-that-remembers";
const IMPORT_VERSION = "1.0.0";
const FLAG = "generated";

Hooks.once("init", () => {
  game.settings.register(MODULE_ID, "importedVersion", {name: "Imported Version", scope: "world", config: false, type: String, default: ""});
  game.settings.register(MODULE_ID, "reefClock", {name: "Reef Clock", scope: "world", config: false, type: Number, default: 0});
});

Hooks.once("ready", async () => {
  const mod = game.modules.get(MODULE_ID);
  mod.api = {importAdventure, fadingDialog, fadingSave, adjustReefClock, rollMistEvent, showImporter};
  if (!game.user.isGM) return;
  const imported = game.settings.get(MODULE_ID, "importedVersion");
  if (imported !== IMPORT_VERSION) showImporter(imported);
});

Hooks.on("renderSettings", (app, html) => {
  if (!game.user.isGM) return;
  const root = html instanceof jQuery ? html : $(html);
  if (root.find(".maurei-import-button").length) return;
  const button = $(`<button type="button" class="maurei-import-button"><i class="fas fa-island-tropical"></i> Import / Refresh Maurei</button>`);
  button.on("click", () => showImporter(game.settings.get(MODULE_ID, "importedVersion")));
  const target = root.find("#settings-game").first();
  (target.length ? target : root).append(button);
});

function showImporter(imported="") {
  new Dialog({
    title: "Maurei, The Isle That Remembers",
    content: `<div class="maurei-dialog"><p>This installs the complete one-shot into the current world: journals, scenes, actors, tokens, roll table, macros, map pins, and pre-positioned hidden encounter tokens.</p>${imported ? `<p><strong>Installed version:</strong> ${imported}. Re-importing replaces content previously generated by this module.</p>` : "<p>No imported content was detected.</p>"}<p>Designed for Foundry V12 and D&D5e 3.3.x.</p></div>`,
    buttons: {
      import: {icon: '<i class="fas fa-file-import"></i>', label: imported ? "Refresh Import" : "Import Adventure", callback: () => importAdventure()},
      cancel: {icon: '<i class="fas fa-times"></i>', label: "Cancel"}
    }, default: "import"
  }).render(true);
}

async function loadData() {
  const r = await fetch(`modules/${MODULE_ID}/data/adventure.json`);
  if (!r.ok) throw new Error(`Unable to load Maurei data (${r.status})`);
  return r.json();
}

async function removeGenerated() {
  const groups = [game.scenes, game.journal, game.actors, game.tables, game.macros];
  for (const collection of groups) {
    for (const doc of [...collection]) if (doc.getFlag(MODULE_ID, FLAG)) await doc.delete();
  }
  for (const folder of [...game.folders]) if (folder.getFlag(MODULE_ID, FLAG)) await folder.delete();
}

async function makeFolder(name, type, color) {
  return Folder.create({name, type, color, sorting: "a", flags: {[MODULE_ID]: {[FLAG]: true}}});
}

function tokenData(actor, spec) {
  const src = actor.prototypeToken.toObject();
  delete src._id;
  src.actorId = actor.id;
  src.actorLink = false;
  src.x = spec.x; src.y = spec.y; src.hidden = spec.hidden ?? true;
  if (spec.texture) src.texture.src = spec.texture;
  if (spec.width) src.width = spec.width;
  if (spec.height) src.height = spec.height;
  return src;
}

async function importAdventure() {
  if (!game.user.isGM) return ui.notifications.error("Only a GM can import Maurei.");
  if (game.system.id !== "dnd5e") return ui.notifications.error("Maurei requires the D&D5e system.");
  const v = game.system.version ?? "0";
  if (!foundry.utils.isNewerVersion(v, "3.2.99") || foundry.utils.isNewerVersion(v, "3.3.99")) {
    ui.notifications.warn(`This module targets D&D5e 3.3.x. Detected ${v}; the import will continue, but actor migration may be required.`);
  }
  ui.notifications.info("Importing Maurei…");
  try {
    const data = await loadData();
    await removeGenerated();
    const folders = {
      actors: await makeFolder("Maurei — Creatures & Vessels", "Actor", "#8ea3a8"),
      journals: await makeFolder("Maurei — Journals", "JournalEntry", "#d4c29b"),
      scenes: await makeFolder("Maurei — Scenes", "Scene", "#44656b"),
      tables: await makeFolder("Maurei — Tables", "RollTable", "#809095"),
      macros: await makeFolder("Maurei — Macros", "Macro", "#b8a16d")
    };

    const actorMap = new Map();
    for (const a of data.actors) {
      const key = a.key; delete a.key;
      a.folder = folders.actors.id;
      const created = await Actor.create(a);
      actorMap.set(key, created);
    }

    const table = await RollTable.create({
      name: "Maurei — Mist-Events", formula: "1d8", folder: folders.tables.id,
      description: "Roll or choose when the party rests, splits, lingers, or pushes deeper into the Pall.",
      results: data.mistEvents.map((r, i) => ({type: 0, text: `<strong>${r.name}.</strong> ${r.text}`, img: "icons/magic/air/fog-gas-smoke-dense-white.webp", range: r.range, weight: 1, drawn: false})),
      ownership: {default: 0}, flags: {[MODULE_ID]: {[FLAG]: true, key: "mist-events"}}
    });

    const macros = [
      ["Maurei — Fading Tracker", `game.modules.get("${MODULE_ID}").api.fadingDialog();`, "icons/magic/control/hypnosis-mesmerism-eye-tan.webp"],
      ["Maurei — Make Fading Save", `game.modules.get("${MODULE_ID}").api.fadingSave();`, "icons/magic/control/fear-fright-monster-grin-red-orange.webp"],
      ["Maurei — Reef Clock", `game.modules.get("${MODULE_ID}").api.adjustReefClock();`, "icons/tools/navigation/compass-brass-blue-red.webp"],
      ["Maurei — Roll Mist-Event", `game.modules.get("${MODULE_ID}").api.rollMistEvent();`, "icons/magic/air/fog-gas-smoke-dense-white.webp"],
      ["Maurei — Refresh Import", `game.modules.get("${MODULE_ID}").api.showImporter(game.settings.get("${MODULE_ID}", "importedVersion"));`, "icons/svg/upgrade.svg"]
    ];
    for (const [name, command, img] of macros) await Macro.create({name,type:"script",command,img,folder:folders.macros.id,ownership:{default:0},flags:{[MODULE_ID]:{[FLAG]:true}}});

    const journalMap = new Map();
    const pageMap = new Map();
    async function createJournal(def, monster=false) {
      const pages = monster ? def.pages.map(pg => ({
        name: pg.name, type: "text", text: {format: 1, content: pg.html.replace(/\{\{actor:([^}]+)\}\}/g, (_, k) => actorMap.get(k)?.id ?? "")},
        title: {show: true, level: 1}, sort: pg.sort, flags: {[MODULE_ID]: {key: pg.key}}
      })) : def.pages;
      const je = await JournalEntry.create({name:def.name,folder:folders.journals.id,pages,ownership:{default:def.ownership},flags:{[MODULE_ID]:{[FLAG]:true,key:def.key}}});
      journalMap.set(def.key, je);
      for (const page of je.pages) pageMap.set(page.getFlag(MODULE_ID,"key"), page);
      return je;
    }
    const gm = await createJournal(data.journals.gm);
    await createJournal(data.journals.player);
    await createJournal(data.journals.monsters, true);

    for (const s of data.scenes) {
      const sceneTokens = s.tokens.map(t => tokenData(actorMap.get(t.actor), t));
      const notes = s.notes.map(n => {
        const pg = pageMap.get(n.page);
        return {entryId: gm.id, pageId: pg?.id ?? null, x:n.x, y:n.y, icon:"icons/svg/book.svg", iconSize:40, text:n.label, textAnchor:1, textColor:"#f4ead0", global:false, flags:{[MODULE_ID]:{[FLAG]:true}}};
      });
      const scene = await Scene.create({
        name:s.name,folder:folders.scenes.id,navigation:s.navigation,navOrder:100,
        background:{src:s.map,offsetX:0,offsetY:0},width:s.width,height:s.height,padding:0.05,backgroundColor:"#101819",
        grid:{type:s.grid ? 1 : 0,size:s.grid || 100,distance:5,units:"ft",color:"#000000",alpha:0.18},
        tokenVision:false,fogExploration:false,globalLight:true,darkness:0,
        tokens:sceneTokens,notes,ownership:{default:s.player ? 2 : 0},flags:{[MODULE_ID]:{[FLAG]:true,key:s.key}}
      });
    }

    await game.settings.set(MODULE_ID,"importedVersion",IMPORT_VERSION);
    await game.settings.set(MODULE_ID,"reefClock",0);
    ui.notifications.info("Maurei imported successfully. Open the Maurei folders in the sidebar.");
    ChatMessage.create({content:`<h2>Maurei Imported</h2><p>The adventure, scenes, actors, journals, Mist-Events table, and automation macros are ready.</p><p><strong>Start with:</strong> <em>Maurei — GM Guide</em> and the <em>Maurei Overview — GM</em> scene.</p>`,whisper:ChatMessage.getWhisperRecipients("GM")});
  } catch (err) {
    console.error(`${MODULE_ID} | Import failed`,err);
    ui.notifications.error(`Maurei import failed: ${err.message}. See the browser console for details.`);
  }
}

function selectedActors() {
  const controlled = canvas?.tokens?.controlled?.map(t => t.actor).filter(Boolean) ?? [];
  if (controlled.length) return [...new Set(controlled)];
  if (game.user.character) return [game.user.character];
  return [];
}

async function changeFading(delta=null, setValue=null) {
  const actors=selectedActors();
  if (!actors.length) return ui.notifications.warn("Select one or more tokens first.");
  const stages=["Clear","Haze","Slip","Drift","Unmooring","Lost"];
  const reports=[];
  for (const actor of actors) {
    const old=Number(actor.getFlag(MODULE_ID,"fading") ?? 0);
    const value=Math.clamp(setValue ?? old+delta,0,5);
    await actor.setFlag(MODULE_ID,"fading",value);
    reports.push(`<li><strong>${actor.name}</strong>: ${stages[old]} → ${stages[value]}</li>`);
  }
  ChatMessage.create({content:`<h3>Fading</h3><ul>${reports.join("")}</ul>`});
}

function fadingDialog() {
  const actors=selectedActors();
  if (!actors.length) return ui.notifications.warn("Select one or more tokens first.");
  const stages=["Clear","Haze","Slip","Drift","Unmooring","Lost"];
  const status=actors.map(a=>`<li>${a.name}: <strong>${stages[Number(a.getFlag(MODULE_ID,"fading") ?? 0)]}</strong></li>`).join("");
  new Dialog({title:"Maurei — Fading Tracker",content:`<p>Selected:</p><ul>${status}</ul>`,buttons:{advance:{label:"Advance +1",callback:()=>changeFading(1)},recover:{label:"Recover −1",callback:()=>changeFading(-1)},reset:{label:"Reset",callback:()=>changeFading(null,0)}},default:"advance"}).render(true);
}

async function fadingSave() {
  const actors=selectedActors();
  if (!actors.length) return ui.notifications.warn("Select one or more tokens first.");
  new Dialog({title:"Maurei — Fading Save",content:`<div class="form-group"><label>Wisdom save DC</label><input id="maurei-dc" type="number" value="13" min="1" max="30"/></div>`,buttons:{roll:{label:"Roll Saves",callback:async html=>{
    const dc=Number(html.find("#maurei-dc").val()||13);
    for(const actor of actors){
      const result=await actor.rollAbilitySave("wis",{fastForward:true,configureDialog:false});
      const total=result?.total ?? result?.rolls?.[0]?.total;
      if(Number.isFinite(total) && total<dc) await changeFadingForActor(actor,1);
    }
  }}},default:"roll"}).render(true);
}

async function changeFadingForActor(actor,delta){
  const old=Number(actor.getFlag(MODULE_ID,"fading")??0); const value=Math.clamp(old+delta,0,5); await actor.setFlag(MODULE_ID,"fading",value);
  const stages=["Clear","Haze","Slip","Drift","Unmooring","Lost"];
  ChatMessage.create({content:`<p><strong>${actor.name}</strong> advances to <strong>${stages[value]}</strong>.</p>`});
}

function reefDisplay(value){return `${"●".repeat(value)}${"○".repeat(6-value)}`;}
function adjustReefClock(){
  const value=Number(game.settings.get(MODULE_ID,"reefClock")??0);
  new Dialog({title:"Maurei — Reef Clock",content:`<p class="maurei-clock">${reefDisplay(value)}</p><p>${value}/6 segments filled.</p>`,buttons:{advance:{label:"Advance",callback:()=>setReefClock(value+1)},reverse:{label:"Reverse",callback:()=>setReefClock(value-1)},reset:{label:"Reset",callback:()=>setReefClock(0)}},default:"advance"}).render(true);
}
async function setReefClock(v){v=Math.clamp(v,0,6);await game.settings.set(MODULE_ID,"reefClock",v);ChatMessage.create({content:`<h3>Reef Clock</h3><p class="maurei-clock">${reefDisplay(v)}</p><p>${v}/6 segments. ${v===6?"<strong>The ship reaches the coral; the Saltwyrm breaks off.</strong>":""}</p>`});}
async function rollMistEvent(){const t=game.tables.find(t=>t.getFlag(MODULE_ID,"key")==="mist-events")??game.tables.getName("Maurei — Mist-Events");if(!t)return ui.notifications.error("Mist-Events table not found.");await t.draw();}
